version: '3.8'

services:
  app:
    build: .
    container_name: my_php_app
    ports:
      - "80:80"
    depends_on:
      - db
    volumes:
      - ./src:/var/www/html

  db:
    image: mysql:8.0
    container_name: my_php_app_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
    volumes:
      - db_data:/var/lib/mysql
      - ./src/resources/databases/:/db
      - ./src/resources/databases/databases_with_test_data.sql:/docker-entrypoint-initdb.d/databases_with_test_data.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: my_php_app_phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: my_user
      PMA_PASSWORD: my_password
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db_data:
